# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170819_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default='www.python.org'),
        ),
    ]
